# Generated by Django 2.2.12 on 2022-04-27 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_parametrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.FloatField()),
                ('contrast', models.FloatField()),
                ('focusing_accurate', models.FloatField()),
                ('focusing_raw', models.FloatField()),
                ('voltage', models.FloatField()),
                ('aperture_size', models.FloatField()),
                ('working_distance', models.FloatField()),
                ('beam_current', models.FloatField()),
                ('astigmatism', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Database_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('group', models.CharField(max_length=15)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.UserProfile')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Image_parametrs')),
            ],
        ),
    ]
