# Generated by Django 2.2.12 on 2022-04-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_database_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='database_entry',
            name='author',
            field=models.CharField(default='Вася', max_length=30),
        ),
    ]
