# Generated by Django 3.2.13 on 2022-05-10 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_database_entry_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presaved_labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('author', models.CharField(default='Вася', max_length=30)),
                ('group', models.CharField(max_length=15)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('brightness', models.FloatField()),
                ('contrast', models.FloatField()),
                ('roughFocus', models.FloatField()),
                ('preciseFocus', models.FloatField()),
                ('voltage', models.FloatField()),
                ('apertureSize', models.FloatField()),
                ('workDistance', models.FloatField()),
                ('beamCurrent', models.FloatField()),
                ('scale', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Saved_labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('author', models.CharField(default='Вася', max_length=30)),
                ('group', models.CharField(max_length=15)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('brightness', models.FloatField()),
                ('contrast', models.FloatField()),
                ('roughFocus', models.FloatField()),
                ('preciseFocus', models.FloatField()),
                ('voltage', models.FloatField()),
                ('apertureSize', models.FloatField()),
                ('workDistance', models.FloatField()),
                ('beamCurrent', models.FloatField()),
                ('scale', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Database_entry',
        ),
        migrations.DeleteModel(
            name='Image_parametrs',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
