# Generated by Django 3.2.13 on 2022-05-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220510_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_labs',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
