# Generated by Django 3.2.13 on 2022-05-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_saved_labs_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('deadline', models.CharField(max_length=20)),
                ('task', models.CharField(max_length=300)),
            ],
        ),
    ]
