# Generated by Django 3.2.13 on 2022-05-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lab_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presaved_labs',
            name='author',
        ),
        migrations.RemoveField(
            model_name='presaved_labs',
            name='group',
        ),
        migrations.RemoveField(
            model_name='saved_labs',
            name='author',
        ),
        migrations.RemoveField(
            model_name='saved_labs',
            name='group',
        ),
        migrations.AddField(
            model_name='lab_description',
            name='title',
            field=models.CharField(default='заголовок', max_length=300),
        ),
        migrations.AddField(
            model_name='presaved_labs',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saved_labs',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lab_description',
            name='task',
            field=models.CharField(max_length=1500),
        ),
    ]
