# Generated by Django 3.2.13 on 2022-05-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220524_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presaved_labs',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
